[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer']

[phases.install]
cmds = [
  'composer install --no-dev --no-scripts --ignore-platform-reqs',
  'composer dump-autoload --optimize --no-scripts'
]

[phases.build]
cmds = [
  'touch database/database.sqlite',
  'php artisan migrate --force || true',
  'php artisan db:seed --force || true'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
